-- Stock buy-signal feature — Supabase schema.
-- Run this once in the Supabase SQL editor (Project → SQL editor → New query → Run).
-- All three tables are service-role only: RLS is enabled with no public policies,
-- so only the bot (using the service key) can read/write them.

create table if not exists public.stock_watchlist (
  id           bigint generated by default as identity primary key,
  ticker       text not null unique,
  company_name text,
  enabled      boolean not null default true,
  created_by   text,
  created_at   timestamptz not null default now(),
  updated_at   timestamptz not null default now()
);

create table if not exists public.stock_signals (
  id                 bigint generated by default as identity primary key,
  ticker             text not null,
  signal_type        text default 'buy',
  score              integer,
  confidence         text,
  price              numeric,
  entry_low          numeric,
  entry_high         numeric,
  support_level      numeric,
  resistance_level   numeric,
  invalidation_level numeric,
  risk_reward_ratio  numeric,
  reasons            jsonb,
  warnings           jsonb,
  market_condition   text,
  message_id         text,          -- Discord message id of the posted alert
  status             text default 'active',
  created_at         timestamptz not null default now(),
  expires_at         timestamptz
);
create index if not exists stock_signals_ticker_created_idx
  on public.stock_signals (ticker, created_at desc);

create table if not exists public.stock_alert_settings (
  id                    integer primary key default 1,
  alerts_enabled        boolean not null default true,
  channel_id            text,
  scan_interval_minutes integer not null default 15,
  signal_min_score      integer not null default 80,
  alert_cooldown_hours  integer not null default 24,
  min_risk_reward       numeric not null default 1.5,
  relvol_threshold      numeric not null default 1.2,
  include_premarket     boolean not null default false,
  include_after_hours   boolean not null default false,
  earnings_block_days   integer not null default 3,
  updated_at            timestamptz not null default now(),
  constraint stock_alert_settings_singleton check (id = 1)
);
insert into public.stock_alert_settings (id) values (1) on conflict (id) do nothing;

alter table public.stock_watchlist      enable row level security;
alter table public.stock_signals        enable row level security;
alter table public.stock_alert_settings enable row level security;

-- Optional starter watchlist (edit or delete as you like; the bot commands can manage it too):
insert into public.stock_watchlist (ticker, company_name) values
  ('AAPL','Apple Inc.'),
  ('MSFT','Microsoft Corporation'),
  ('NVDA','NVIDIA Corporation'),
  ('AMZN','Amazon.com Inc.'),
  ('GOOGL','Alphabet Inc.'),
  ('META','Meta Platforms Inc.'),
  ('TSLA','Tesla Inc.'),
  ('AMD','Advanced Micro Devices Inc.')
on conflict (ticker) do nothing;
