-- Track supplier balance deposits separately from sales, costs, and profit.
-- Run once in the Supabase SQL editor before using /invest with a supplier.

create table if not exists public.reseller_investments (
  id bigint generated by default as identity primary key,
  amount_cents integer not null check (amount_cents > 0),
  supplier text not null default 'unassigned',
  note text,
  created_at timestamptz not null default now()
);

alter table public.reseller_investments
  add column if not exists supplier text not null default 'unassigned';

update public.reseller_investments
set supplier = 'unassigned'
where supplier is null or btrim(supplier) = '';

alter table public.reseller_investments
  alter column supplier set default 'unassigned',
  alter column supplier set not null;

create index if not exists reseller_investments_supplier_created_idx
  on public.reseller_investments (supplier, created_at);

alter table public.reseller_investments enable row level security;
