-- Persistent, deploy-safe state for the private finance-health monitor.
-- Run once in the Supabase SQL editor before enabling scheduled reports.

create table if not exists public.finance_health_snapshots (
  id bigint generated by default as identity primary key,
  checked_at timestamptz not null default now(),
  status text not null check (status in ('healthy', 'warning', 'loss')),
  fingerprint text not null,
  alerted boolean not null default false,
  last_alerted_at timestamptz,
  payload jsonb not null default '{}'::jsonb
);

alter table public.finance_health_snapshots
  add column if not exists last_alerted_at timestamptz;

create index if not exists finance_health_snapshots_checked_idx
  on public.finance_health_snapshots (checked_at desc);

create index if not exists finance_health_snapshots_status_checked_idx
  on public.finance_health_snapshots (status, checked_at desc);

alter table public.finance_health_snapshots enable row level security;
