-- Deterministic Safe-to-Reinvest, simulation funding plans, and FIFO batch
-- attribution. All tables are private service-role tables; no client role is
-- granted access. The seeded mode is simulation so no payment can move money.

create table if not exists public.finance_settings (
  id smallint primary key default 1 check (id = 1),
  mode text not null default 'simulation' check (mode in ('simulation', 'approval', 'auto')),
  primary_supplier text not null default 'cheatslove',
  primary_supplier_allocation_percent integer not null default 100 check (primary_supplier_allocation_percent between 0 and 100),
  minimum_reserve_cents integer not null default 0 check (minimum_reserve_cents >= 0),
  safety_margin_hours numeric(10,2) not null default 3 check (safety_margin_hours >= 0),
  expected_funding_hours numeric(10,2) not null default 12 check (expected_funding_hours >= 0),
  minimum_target_runway_hours numeric(10,2) not null default 2 check (minimum_target_runway_hours >= 0),
  dynamic_reserve_hours numeric(10,2) not null default 0.75 check (dynamic_reserve_hours >= 0),
  max_transaction_cents integer not null default 0 check (max_transaction_cents >= 0),
  max_daily_reinvestment_cents integer not null default 0 check (max_daily_reinvestment_cents >= 0),
  minimum_confidence text not null default 'medium' check (minimum_confidence in ('low', 'medium', 'high')),
  max_data_age_minutes integer not null default 15 check (max_data_age_minutes > 0),
  notifications_enabled boolean not null default false,
  paused boolean not null default false,
  updated_at timestamptz not null default now()
);

insert into public.finance_settings (id) values (1)
on conflict (id) do nothing;

create table if not exists public.finance_supplier_balance_snapshots (
  id bigint generated by default as identity primary key,
  supplier text not null,
  balance_cents integer not null check (balance_cents >= 0),
  available boolean not null default true,
  source text not null default 'api',
  captured_at timestamptz not null default now(),
  raw jsonb not null default '{}'::jsonb
);
create index if not exists finance_supplier_balance_snapshots_idx
  on public.finance_supplier_balance_snapshots (supplier, captured_at desc);

create table if not exists public.finance_supplier_transactions (
  id bigint generated by default as identity primary key,
  supplier text not null,
  external_id text not null,
  transaction_type text not null check (transaction_type in ('deposit', 'order', 'credit', 'refund', 'adjustment', 'unknown')),
  amount_cents integer not null,
  status text not null default 'confirmed' check (status in ('pending', 'confirmed', 'failed', 'reversed')),
  occurred_at timestamptz not null,
  source text not null default 'api',
  metadata jsonb not null default '{}'::jsonb,
  created_at timestamptz not null default now(),
  unique (supplier, external_id)
);
create index if not exists finance_supplier_transactions_time_idx
  on public.finance_supplier_transactions (supplier, occurred_at desc);

create table if not exists public.finance_coinbase_balance_snapshots (
  id bigint generated by default as identity primary key,
  asset text not null default 'USDC',
  balance_cents integer not null check (balance_cents >= 0),
  source text not null default 'manual',
  captured_at timestamptz not null default now(),
  raw jsonb not null default '{}'::jsonb
);
create index if not exists finance_coinbase_balance_snapshots_idx
  on public.finance_coinbase_balance_snapshots (asset, captured_at desc);

create table if not exists public.finance_sync_runs (
  id bigint generated by default as identity primary key,
  source text not null check (source in ('stripe', 'cheatslove', 'coinbase', 'orders', 'worker')),
  status text not null check (status in ('running', 'complete', 'failed', 'needs_attention')),
  started_at timestamptz not null default now(),
  finished_at timestamptz,
  records_seen integer not null default 0 check (records_seen >= 0),
  error text,
  metadata jsonb not null default '{}'::jsonb
);
create index if not exists finance_sync_runs_source_time_idx
  on public.finance_sync_runs (source, started_at desc);

create table if not exists public.finance_funding_plans (
  id uuid primary key default gen_random_uuid(),
  supplier text not null,
  mode text not null check (mode in ('simulation', 'approval', 'auto')),
  status text not null default 'proposed' check (status in ('proposed', 'blocked', 'approved', 'submitted', 'confirmed', 'simulation_complete', 'rejected', 'expired')),
  safe_to_reinvest_cents integer not null default 0 check (safe_to_reinvest_cents >= 0),
  ideal_topup_cents integer not null default 0 check (ideal_topup_cents >= 0),
  unfunded_need_cents integer not null default 0 check (unfunded_need_cents >= 0),
  confidence text not null check (confidence in ('low', 'medium', 'high')),
  simulation boolean not null default true,
  reason text not null default '',
  decision jsonb not null default '{}'::jsonb,
  decision_fingerprint text,
  approved_at timestamptz,
  approval_expires_at timestamptz,
  approval_invalidated_at timestamptz,
  approved_by text,
  submitted_at timestamptz,
  confirmed_at timestamptz,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);
create index if not exists finance_funding_plans_created_idx
  on public.finance_funding_plans (created_at desc);
create index if not exists finance_funding_plans_status_idx
  on public.finance_funding_plans (status, created_at desc);
do $$
begin
  alter table public.finance_funding_plans
    add constraint finance_funding_plans_decision_fingerprint_key unique (decision_fingerprint);
exception when duplicate_object then null;
end $$;

create table if not exists public.finance_reinvestment_batches (
  id uuid primary key default gen_random_uuid(),
  supplier text not null,
  funding_plan_id uuid references public.finance_funding_plans(id) on delete set null,
  source_transaction_id text,
  amount_cents integer not null check (amount_cents > 0),
  verified_amount_cents integer not null default 0 check (verified_amount_cents >= 0),
  confidence text not null check (confidence in ('low', 'medium', 'high')),
  starting_balance_cents integer not null default 0 check (starting_balance_cents >= 0),
  capital_remaining_cents integer not null check (capital_remaining_cents >= 0),
  capital_consumed_cents integer not null default 0 check (capital_consumed_cents >= 0),
  revenue_attributed_cents integer not null default 0 check (revenue_attributed_cents >= 0),
  refunds_attributed_cents integer not null default 0 check (refunds_attributed_cents >= 0),
  gross_profit_cents integer not null default 0,
  status text not null default 'ACTIVE' check (status in ('ACTIVE', 'FULLY_DEPLOYED', 'COMPLETED', 'ADJUSTED')),
  simulation boolean not null default true,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);
create index if not exists finance_reinvestment_batches_supplier_idx
  on public.finance_reinvestment_batches (supplier, created_at);
create index if not exists finance_reinvestment_batches_status_idx
  on public.finance_reinvestment_batches (status, created_at desc);

create table if not exists public.finance_reinvestment_allocations (
  id bigint generated by default as identity primary key,
  batch_id uuid not null references public.finance_reinvestment_batches(id) on delete cascade,
  order_id uuid not null references public.orders(id) on delete cascade,
  supplier_cost_cents integer not null check (supplier_cost_cents >= 0),
  revenue_cents integer not null default 0 check (revenue_cents >= 0),
  refund_cents integer not null default 0 check (refund_cents >= 0),
  funding_fraction numeric(12,8) not null default 0 check (funding_fraction >= 0 and funding_fraction <= 1),
  created_at timestamptz not null default now(),
  unique (batch_id, order_id)
);
create index if not exists finance_reinvestment_allocations_order_idx
  on public.finance_reinvestment_allocations (order_id);

create table if not exists public.finance_audit_events (
  id bigint generated by default as identity primary key,
  event_type text not null,
  source text not null default 'worker',
  entity_type text,
  entity_id text,
  simulation boolean not null default true,
  details jsonb not null default '{}'::jsonb,
  created_at timestamptz not null default now()
);
create index if not exists finance_audit_events_created_idx
  on public.finance_audit_events (created_at desc);
create index if not exists finance_audit_events_entity_idx
  on public.finance_audit_events (entity_type, entity_id, created_at desc);

do $$
declare
  table_name text;
begin
  foreach table_name in array array[
    'finance_settings',
    'finance_supplier_balance_snapshots',
    'finance_supplier_transactions',
    'finance_coinbase_balance_snapshots',
    'finance_sync_runs',
    'finance_funding_plans',
    'finance_reinvestment_batches',
    'finance_reinvestment_allocations',
    'finance_audit_events'
  ] loop
    execute format('alter table public.%I enable row level security', table_name);
    execute format('revoke all on table public.%I from anon, authenticated', table_name);
    execute format('drop policy if exists finance_private_deny_public on public.%I', table_name);
    execute format('create policy finance_private_deny_public on public.%I for all to anon, authenticated using (false) with check (false)', table_name);
  end loop;
end $$;
